services:
  - type: web
    name: farmabol-inventario
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
